version: "3.8"

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ollama
      - chroma
    environment:
      LLM_MODEL: mistral
      CHROMA_PATH: /chroma
      COLLECTION_NAME: local-rag
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  chroma_data:
    driver: local
