services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - TEMP_FOLDER=/app/data
      - CHUNK_SIZE=1024
      - CHUNK_OVERLAP=100
      - LLM_MODEL=llama3.2
    volumes:
      - ./data:/app/data
    depends_on:
      - chromadb
      - ollama

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db:/chroma/chroma_db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  chroma_db: